name: Teste SWAPI - Pessoa inexistente

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar dependências
        run: npm install

      - name: Rodar teste para pessoa inexistente
        run: npx jest -t "Retorna erro 404 ao pesquisar uma pessoa inexistente"